### ISSUE TITLE
Is there any documentation of this repo? 

### ISSUE THREAD

**Issue by manishAirbotix** [mortenjc/lang#1]
I want to use the melp codec from your repo, but could not find any clue where to start from.

**Comment by mortenjc** [comment]
Unfortunetely what you see in the MELP folder is all there is. It has been years since I played with this
but in principle you can build it using the Makefile and there are some instructions in the README

However beware that the code is copyright Texas Instruments. So using this commercially would require 
a license agreement.

**Comment by manishAirbotix** [comment]
Thank you for the clarification. I will ensure that any use of this code complies with the licensing requirements.
